// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/circuit/circuit.proto
// DO NOT EDIT!

/*
Package circuit is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/quic-channel/circuit/circuit.proto
	github.com/fuserobotics/quic-channel/circuit/control.proto

It has these top-level messages:
	CircuitProbe
	CircuitProbeRequest
	SessionInit
	KeepAlive
*/
package circuit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import route "github.com/fuserobotics/quic-channel/route"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EStreamType are the types of Circuit streams.
type EStreamType int32

const (
	// Control stream, used for control messages.
	EStreamType_STREAM_CONTROL EStreamType = 0
)

var EStreamType_name = map[int32]string{
	0: "STREAM_CONTROL",
}
var EStreamType_value = map[string]int32{
	"STREAM_CONTROL": 0,
}

func (x EStreamType) String() string {
	return proto.EnumName(EStreamType_name, int32(x))
}
func (EStreamType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// CircuitProbe is a probe to build a circuit.
type CircuitProbe struct {
	// Route contains the route so far.
	Route *route.Route `protobuf:"bytes,1,opt,name=route" json:"route,omitempty"`
}

func (m *CircuitProbe) Reset()                    { *m = CircuitProbe{} }
func (m *CircuitProbe) String() string            { return proto.CompactTextString(m) }
func (*CircuitProbe) ProtoMessage()               {}
func (*CircuitProbe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CircuitProbe) GetRoute() *route.Route {
	if m != nil {
		return m.Route
	}
	return nil
}

// CircuitProbeRequest is the information about the CircuitProbe.
type CircuitProbeRequest struct {
}

func (m *CircuitProbeRequest) Reset()                    { *m = CircuitProbeRequest{} }
func (m *CircuitProbeRequest) String() string            { return proto.CompactTextString(m) }
func (*CircuitProbeRequest) ProtoMessage()               {}
func (*CircuitProbeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CircuitProbe)(nil), "circuit.CircuitProbe")
	proto.RegisterType((*CircuitProbeRequest)(nil), "circuit.CircuitProbeRequest")
	proto.RegisterEnum("circuit.EStreamType", EStreamType_name, EStreamType_value)
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/circuit/circuit.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2b, 0x2d, 0x4e, 0x2d, 0xca, 0x4f, 0xca, 0x2f,
	0xc9, 0x4c, 0x2e, 0xd6, 0x2f, 0x2c, 0xcd, 0x4c, 0xd6, 0x4d, 0xce, 0x48, 0xcc, 0xcb, 0x4b, 0xcd,
	0xd1, 0x4f, 0xce, 0x2c, 0x4a, 0x2e, 0xcd, 0x2c, 0x81, 0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0xec, 0x50, 0xae, 0x94, 0x19, 0x51, 0x86, 0x14, 0xe5, 0x97, 0x96, 0xa4, 0x42, 0x48, 0x88,
	0x01, 0x4a, 0x46, 0x5c, 0x3c, 0xce, 0x10, 0x23, 0x02, 0x8a, 0xf2, 0x93, 0x52, 0x85, 0x94, 0xb8,
	0x58, 0xc1, 0xd2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x3c, 0x7a, 0x10, 0xc5, 0x41, 0x20,
	0x32, 0x08, 0x22, 0xa5, 0x24, 0xca, 0x25, 0x8c, 0xac, 0x27, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8,
	0x44, 0x4b, 0x91, 0x8b, 0xdb, 0x35, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0x37, 0xa4, 0xb2, 0x20, 0x55,
	0x48, 0x88, 0x8b, 0x2f, 0x38, 0x24, 0xc8, 0xd5, 0xd1, 0x37, 0xde, 0xd9, 0xdf, 0x2f, 0x24, 0xc8,
	0xdf, 0x47, 0x80, 0x21, 0x89, 0x0d, 0x6c, 0xa9, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xab, 0xf3,
	0x49, 0xbc, 0xf3, 0x00, 0x00, 0x00,
}
