// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/circuit/circuit.proto
// DO NOT EDIT!

/*
Package circuit is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/quic-channel/circuit/circuit.proto
	github.com/fuserobotics/quic-channel/circuit/control.proto

It has these top-level messages:
	CircuitProbe
	CircuitInit
	CircuitPacket
	SessionInitChallenge
	SessionInitResponse
	SessionChallenge
	SessionChallengeResponse
	KeepAlive
*/
package circuit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import route "github.com/fuserobotics/quic-channel/route"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EStreamType are the types of Circuit streams.
type EStreamType int32

const (
	// Control stream, used for control messages.
	EStreamType_STREAM_CONTROL EStreamType = 0
	// Circuit stream, used for building circuits.
	EStreamType_STREAM_CIRCUIT EStreamType = 1
)

var EStreamType_name = map[int32]string{
	0: "STREAM_CONTROL",
	1: "STREAM_CIRCUIT",
}
var EStreamType_value = map[string]int32{
	"STREAM_CONTROL": 0,
	"STREAM_CIRCUIT": 1,
}

func (x EStreamType) String() string {
	return proto.EnumName(EStreamType_name, int32(x))
}
func (EStreamType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// CircuitProbe is a probe to build a circuit.
// control packet_type: 5
type CircuitProbe struct {
	// Route contains the route so far.
	Route *route.Route `protobuf:"bytes,1,opt,name=route" json:"route,omitempty"`
}

func (m *CircuitProbe) Reset()                    { *m = CircuitProbe{} }
func (m *CircuitProbe) String() string            { return proto.CompactTextString(m) }
func (*CircuitProbe) ProtoMessage()               {}
func (*CircuitProbe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CircuitProbe) GetRoute() *route.Route {
	if m != nil {
		return m.Route
	}
	return nil
}

// CircuitInit is the first message on the circuit stream.
// circuit packet_type: 1
type CircuitInit struct {
	// RouteEstablish is the route establish chain.
	RouteEstablish *route.RouteEstablish `protobuf:"bytes,1,opt,name=route_establish,json=routeEstablish" json:"route_establish,omitempty"`
}

func (m *CircuitInit) Reset()                    { *m = CircuitInit{} }
func (m *CircuitInit) String() string            { return proto.CompactTextString(m) }
func (*CircuitInit) ProtoMessage()               {}
func (*CircuitInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CircuitInit) GetRouteEstablish() *route.RouteEstablish {
	if m != nil {
		return m.RouteEstablish
	}
	return nil
}

// CircuitPacket is a packet sent over the circuit.
// circuit packet_type 2
type CircuitPacket struct {
	// PacketData is the data in the packet.
	PacketData []byte `protobuf:"bytes,1,opt,name=packet_data,json=packetData,proto3" json:"packet_data,omitempty"`
}

func (m *CircuitPacket) Reset()                    { *m = CircuitPacket{} }
func (m *CircuitPacket) String() string            { return proto.CompactTextString(m) }
func (*CircuitPacket) ProtoMessage()               {}
func (*CircuitPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CircuitPacket) GetPacketData() []byte {
	if m != nil {
		return m.PacketData
	}
	return nil
}

func init() {
	proto.RegisterType((*CircuitProbe)(nil), "circuit.CircuitProbe")
	proto.RegisterType((*CircuitInit)(nil), "circuit.CircuitInit")
	proto.RegisterType((*CircuitPacket)(nil), "circuit.CircuitPacket")
	proto.RegisterEnum("circuit.EStreamType", EStreamType_name, EStreamType_value)
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/circuit/circuit.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x8f, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xed, 0xa0, 0xc2, 0x6b, 0x3d, 0x8f, 0x80, 0x20, 0x2e, 0x4a, 0x27, 0x11, 0x6c, 0xe5,
	0x44, 0x07, 0x07, 0x41, 0x6a, 0x87, 0x82, 0xe7, 0x49, 0xae, 0xce, 0x25, 0x89, 0xd1, 0x06, 0xef,
	0x9a, 0x9a, 0xbc, 0x0c, 0xfe, 0xf7, 0x62, 0xd2, 0x42, 0xdd, 0x5c, 0x5e, 0xf2, 0x7d, 0x5f, 0xbe,
	0x1f, 0x79, 0x70, 0xf7, 0xa1, 0xb0, 0x75, 0x3c, 0x13, 0x7a, 0x9b, 0xbf, 0x3b, 0x2b, 0x8d, 0xe6,
	0x1a, 0x95, 0xb0, 0xf9, 0x97, 0x53, 0xe2, 0x52, 0xb4, 0xac, 0xeb, 0xe4, 0x26, 0x17, 0xca, 0x08,
	0xa7, 0x70, 0x3c, 0xb3, 0xde, 0x68, 0xd4, 0x64, 0x7f, 0x90, 0x27, 0xb7, 0xff, 0x82, 0x18, 0xed,
	0x50, 0x86, 0x19, 0x00, 0xe9, 0x02, 0x92, 0x22, 0x20, 0x5e, 0x8c, 0xe6, 0x92, 0xa4, 0xb0, 0xeb,
	0xe3, 0xe3, 0xe8, 0x2c, 0x3a, 0x8f, 0x17, 0x49, 0x16, 0x1e, 0xd3, 0xdf, 0x49, 0x43, 0x94, 0x2e,
	0x21, 0x1e, 0x3a, 0x55, 0xa7, 0x90, 0xdc, 0xc3, 0xa1, 0xf7, 0x1b, 0x69, 0x91, 0xf1, 0x8d, 0xb2,
	0xed, 0x50, 0x3e, 0x9a, 0x96, 0xcb, 0x31, 0xa4, 0x33, 0xf3, 0x47, 0xa7, 0x57, 0x70, 0x30, 0x7e,
	0x81, 0x89, 0x4f, 0x89, 0xe4, 0x14, 0xe2, 0xde, 0xdf, 0x9a, 0x37, 0x86, 0xcc, 0xc3, 0x12, 0x0a,
	0xc1, 0x7a, 0x64, 0xc8, 0x2e, 0x6e, 0x20, 0x2e, 0xd7, 0x68, 0x24, 0xdb, 0xd6, 0xdf, 0xbd, 0x24,
	0x04, 0x66, 0xeb, 0x9a, 0x96, 0x0f, 0xcb, 0xa6, 0x58, 0x3d, 0xd7, 0x74, 0xf5, 0x34, 0xdf, 0x99,
	0x7a, 0x15, 0x2d, 0x5e, 0xab, 0x7a, 0x1e, 0xf1, 0x3d, 0xbf, 0xf2, 0xf5, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x50, 0x09, 0x83, 0x57, 0x71, 0x01, 0x00, 0x00,
}
