// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/circuit/circuit.proto
// DO NOT EDIT!

/*
Package circuit is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/quic-channel/circuit/circuit.proto
	github.com/fuserobotics/quic-channel/circuit/control.proto

It has these top-level messages:
	ControlSessionInit
	ControlKeepAlive
*/
package circuit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EStreamType are the types of Circuit streams.
type EStreamType int32

const (
	// Control stream, used for control messages.
	EStreamType_STREAM_CONTROL EStreamType = 0
)

var EStreamType_name = map[int32]string{
	0: "STREAM_CONTROL",
}
var EStreamType_value = map[string]int32{
	"STREAM_CONTROL": 0,
}

func (x EStreamType) String() string {
	return proto.EnumName(EStreamType_name, int32(x))
}
func (EStreamType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("circuit.EStreamType", EStreamType_name, EStreamType_value)
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/circuit/circuit.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2b, 0x2d, 0x4e, 0x2d, 0xca, 0x4f, 0xca, 0x2f,
	0xc9, 0x4c, 0x2e, 0xd6, 0x2f, 0x2c, 0xcd, 0x4c, 0xd6, 0x4d, 0xce, 0x48, 0xcc, 0xcb, 0x4b, 0xcd,
	0xd1, 0x4f, 0xce, 0x2c, 0x4a, 0x2e, 0xcd, 0x2c, 0x81, 0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0xec, 0x50, 0xae, 0x96, 0x22, 0x17, 0xb7, 0x6b, 0x70, 0x49, 0x51, 0x6a, 0x62, 0x6e, 0x48,
	0x65, 0x41, 0xaa, 0x90, 0x10, 0x17, 0x5f, 0x70, 0x48, 0x90, 0xab, 0xa3, 0x6f, 0xbc, 0xb3, 0xbf,
	0x5f, 0x48, 0x90, 0xbf, 0x8f, 0x00, 0x43, 0x12, 0x1b, 0x58, 0x8b, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xc9, 0x33, 0xd6, 0x8e, 0x70, 0x00, 0x00, 0x00,
}
