// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/circuit/control.proto
// DO NOT EDIT!

package circuit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/fuserobotics/quic-channel/route"
import identity "github.com/fuserobotics/quic-channel/identity"
import signature "github.com/fuserobotics/quic-channel/signature"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// SessionInitChallenge challenges the client with a salt.
// packet_type: 2
type SessionInitChallenge struct {
	// Timestamp is the time the server began the session.
	// In case of a dispute, the oldest session will be kept.
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Challenge is the session challenge data.
	Challenge *SessionChallenge `protobuf:"bytes,2,opt,name=challenge" json:"challenge,omitempty"`
}

func (m *SessionInitChallenge) Reset()                    { *m = SessionInitChallenge{} }
func (m *SessionInitChallenge) String() string            { return proto.CompactTextString(m) }
func (*SessionInitChallenge) ProtoMessage()               {}
func (*SessionInitChallenge) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *SessionInitChallenge) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SessionInitChallenge) GetChallenge() *SessionChallenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

// SessionInitResponse responds to the SessionInitChallenge.
// packet_type: 3, third message in first control stream.
// Completes the handshake for the session.
type SessionInitResponse struct {
	// Signature is the signed SessionChallengeResponse, usually with a salt.
	Signature *signature.SignedMessage `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
}

func (m *SessionInitResponse) Reset()                    { *m = SessionInitResponse{} }
func (m *SessionInitResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionInitResponse) ProtoMessage()               {}
func (*SessionInitResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *SessionInitResponse) GetSignature() *signature.SignedMessage {
	if m != nil {
		return m.Signature
	}
	return nil
}

// SessionChallenge is the message the server asks the client to sign.
type SessionChallenge struct {
	// ChallengeNonce is a random bit string for the challenge.
	ChallengeNonce []byte `protobuf:"bytes,1,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"`
}

func (m *SessionChallenge) Reset()                    { *m = SessionChallenge{} }
func (m *SessionChallenge) String() string            { return proto.CompactTextString(m) }
func (*SessionChallenge) ProtoMessage()               {}
func (*SessionChallenge) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *SessionChallenge) GetChallengeNonce() []byte {
	if m != nil {
		return m.ChallengeNonce
	}
	return nil
}

// SessionChallengeResponse is the signed challenge response.
type SessionChallengeResponse struct {
	// Challenge is the challenge we are responding to repeated again.
	Challenge *SessionChallenge `protobuf:"bytes,1,opt,name=challenge" json:"challenge,omitempty"`
	// Identity is the identity of the peer.
	Identity *identity.Identity `protobuf:"bytes,2,opt,name=identity" json:"identity,omitempty"`
}

func (m *SessionChallengeResponse) Reset()                    { *m = SessionChallengeResponse{} }
func (m *SessionChallengeResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionChallengeResponse) ProtoMessage()               {}
func (*SessionChallengeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SessionChallengeResponse) GetChallenge() *SessionChallenge {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (m *SessionChallengeResponse) GetIdentity() *identity.Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

// ControlKeepAlive is a keep alive packet.
// packet_type: 4, sent periodically to hold the conn open.
type KeepAlive struct {
}

func (m *KeepAlive) Reset()                    { *m = KeepAlive{} }
func (m *KeepAlive) String() string            { return proto.CompactTextString(m) }
func (*KeepAlive) ProtoMessage()               {}
func (*KeepAlive) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func init() {
	proto.RegisterType((*SessionInitChallenge)(nil), "circuit.SessionInitChallenge")
	proto.RegisterType((*SessionInitResponse)(nil), "circuit.SessionInitResponse")
	proto.RegisterType((*SessionChallenge)(nil), "circuit.SessionChallenge")
	proto.RegisterType((*SessionChallengeResponse)(nil), "circuit.SessionChallengeResponse")
	proto.RegisterType((*KeepAlive)(nil), "circuit.KeepAlive")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/circuit/control.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x51, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0x22, 0x6a, 0xb6, 0xa2, 0xb2, 0x7a, 0x88, 0xc5, 0x43, 0xc9, 0xc5, 0x5e, 0xdc, 0x40,
	0x85, 0x0a, 0x2a, 0x82, 0x78, 0x2a, 0x52, 0x0f, 0xe9, 0x03, 0x48, 0xba, 0x1d, 0xd3, 0x81, 0x64,
	0x36, 0x66, 0x27, 0x82, 0x67, 0x5f, 0x5c, 0xda, 0x24, 0x1b, 0x7f, 0x2e, 0xb9, 0x2c, 0xc3, 0xb7,
	0xf3, 0xfd, 0xcc, 0x8c, 0xb8, 0x4d, 0x91, 0xd7, 0xd5, 0x52, 0x69, 0x93, 0x47, 0x6f, 0x95, 0x85,
	0xd2, 0x2c, 0x0d, 0xa3, 0xb6, 0xd1, 0x7b, 0x85, 0xfa, 0x4a, 0xaf, 0x13, 0x22, 0xc8, 0x22, 0x8d,
	0xa5, 0xae, 0x90, 0x23, 0x6d, 0x88, 0x4b, 0x93, 0xa9, 0xa2, 0x34, 0x6c, 0xe4, 0x7e, 0x03, 0x0f,
	0xa7, 0xbd, 0x44, 0x4a, 0x53, 0x31, 0xd4, 0x6f, 0x2d, 0x30, 0xbc, 0xef, 0xc5, 0xc3, 0x15, 0x10,
	0x23, 0x7f, 0xba, 0xa2, 0x61, 0x3f, 0xf4, 0x62, 0x5b, 0x4c, 0x29, 0xe1, 0xaa, 0x84, 0xae, 0xaa,
	0xf9, 0x61, 0x2e, 0xce, 0x16, 0x60, 0x2d, 0x1a, 0x9a, 0x11, 0xf2, 0xd3, 0x3a, 0xc9, 0x32, 0xa0,
	0x14, 0xe4, 0x85, 0xf0, 0x19, 0x73, 0xb0, 0x9c, 0xe4, 0x45, 0xe0, 0x8d, 0xbc, 0xf1, 0x6e, 0xdc,
	0x01, 0xf2, 0x46, 0xf8, 0xba, 0x6d, 0x0d, 0x76, 0x46, 0xde, 0x78, 0x30, 0x39, 0x57, 0xcd, 0x22,
	0x54, 0xa3, 0xe7, 0xb4, 0xe2, 0xae, 0x37, 0x9c, 0x8b, 0xd3, 0x1f, 0x76, 0x31, 0xd8, 0xc2, 0x90,
	0x05, 0x39, 0x15, 0xbe, 0x0b, 0xb6, 0x75, 0x1b, 0x4c, 0x02, 0xd5, 0x45, 0x5d, 0x60, 0x4a, 0xb0,
	0x9a, 0x83, 0xb5, 0xc9, 0x46, 0xce, 0x7d, 0x84, 0x77, 0xe2, 0xe4, 0xaf, 0x9b, 0xbc, 0x14, 0xc7,
	0xce, 0xef, 0x95, 0x0c, 0xe9, 0x5a, 0xf1, 0x30, 0x3e, 0x72, 0xf0, 0xcb, 0x06, 0x0d, 0xbf, 0x3c,
	0x11, 0xfc, 0xcb, 0xda, 0x26, 0xfa, 0x35, 0xa1, 0xd7, 0x7f, 0x42, 0xa9, 0xc4, 0x41, 0x7b, 0xa2,
	0x66, 0x33, 0x52, 0xb9, 0x9b, 0xcd, 0x9a, 0x22, 0x76, 0x3d, 0xe1, 0x40, 0xf8, 0xcf, 0x00, 0xc5,
	0x63, 0x86, 0x1f, 0xb0, 0xdc, 0xdb, 0x1e, 0xe5, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xb3,
	0x4b, 0x10, 0x91, 0x02, 0x00, 0x00,
}
