// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/circuit/control.proto
// DO NOT EDIT!

package circuit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import route "github.com/fuserobotics/quic-channel/route"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ControlSessionInit initializes the session.
// packet_type: 2, second message in first control stream.
// Completes the handshake for the session.
type SessionInit struct {
	// Timestamp is the time the originator began the session.
	// In case of a dispute, the oldest session will be kept.
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *SessionInit) Reset()                    { *m = SessionInit{} }
func (m *SessionInit) String() string            { return proto.CompactTextString(m) }
func (*SessionInit) ProtoMessage()               {}
func (*SessionInit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *SessionInit) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// ControlKeepAlive is a keep alive packet.
// packet_type: 3, sent periodically to hold the conn open.
type KeepAlive struct {
}

func (m *KeepAlive) Reset()                    { *m = KeepAlive{} }
func (m *KeepAlive) String() string            { return proto.CompactTextString(m) }
func (*KeepAlive) ProtoMessage()               {}
func (*KeepAlive) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// CircuitProbe is an attempt to build a circuit.
// packet_type: 4
type CircuitProbe struct {
	Route *route.Route `protobuf:"bytes,1,opt,name=route" json:"route,omitempty"`
}

func (m *CircuitProbe) Reset()                    { *m = CircuitProbe{} }
func (m *CircuitProbe) String() string            { return proto.CompactTextString(m) }
func (*CircuitProbe) ProtoMessage()               {}
func (*CircuitProbe) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CircuitProbe) GetRoute() *route.Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionInit)(nil), "circuit.SessionInit")
	proto.RegisterType((*KeepAlive)(nil), "circuit.KeepAlive")
	proto.RegisterType((*CircuitProbe)(nil), "circuit.CircuitProbe")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/circuit/control.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x8d, 0x31, 0xeb, 0xc2, 0x30,
	0x10, 0x47, 0x29, 0xfc, 0xff, 0x4a, 0xd3, 0x4e, 0x9d, 0x44, 0x1c, 0x24, 0x93, 0x20, 0x36, 0x50,
	0xc1, 0xc1, 0x4d, 0x9c, 0xc4, 0x45, 0xea, 0x27, 0x68, 0xc2, 0x69, 0x0f, 0xda, 0x5c, 0x4d, 0x2e,
	0x7e, 0x7e, 0xb1, 0x11, 0x5c, 0x5d, 0x7e, 0xc3, 0x3b, 0xee, 0x3d, 0xb1, 0xbf, 0x23, 0xb7, 0x41,
	0x97, 0x86, 0x7a, 0x75, 0x0b, 0x1e, 0x1c, 0x69, 0x62, 0x34, 0x5e, 0x3d, 0x02, 0x9a, 0x8d, 0x69,
	0x1b, 0x6b, 0xa1, 0x53, 0x06, 0x9d, 0x09, 0xc8, 0xca, 0x90, 0x65, 0x47, 0x5d, 0x39, 0x38, 0x62,
	0x2a, 0xa6, 0x1f, 0x3c, 0xdf, 0xfd, 0x24, 0x71, 0x14, 0x18, 0xe2, 0x46, 0x81, 0x5c, 0x8b, 0xec,
	0x0a, 0xde, 0x23, 0xd9, 0x93, 0x45, 0x2e, 0x16, 0x22, 0x65, 0xec, 0xc1, 0x73, 0xd3, 0x0f, 0xb3,
	0x64, 0x99, 0xac, 0xfe, 0xea, 0x2f, 0x90, 0x99, 0x48, 0xcf, 0x00, 0xc3, 0xa1, 0xc3, 0x27, 0xc8,
	0x4a, 0xe4, 0xc7, 0x18, 0xbf, 0x38, 0xd2, 0x50, 0x48, 0xf1, 0x3f, 0x8a, 0xc7, 0xb7, 0xac, 0xca,
	0xcb, 0x98, 0xa9, 0xdf, 0x5b, 0xc7, 0x93, 0x9e, 0x8c, 0xd1, 0xed, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x77, 0x69, 0x85, 0x97, 0xf3, 0x00, 0x00, 0x00,
}
