// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/discovery/discovery.proto
// DO NOT EDIT!

/*
Package discovery is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/quic-channel/discovery/discovery.proto

It has these top-level messages:
	DiscoveryEvent
	DiscoveryUDPPacket
*/
package discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// DiscoveryEventKind are kinds of discovery events.
type DiscoveryEventKind int32

const (
	// When a UDP broadcast is observed over LAN
	DiscoveryEventKind_DISCOVER_OBSERVED_BROADCAST DiscoveryEventKind = 0
	// When the internet connection with this peer is established.
	DiscoveryEventKind_DISCOVER_INET_CONN_ESTABLISHED DiscoveryEventKind = 1
)

var DiscoveryEventKind_name = map[int32]string{
	0: "DISCOVER_OBSERVED_BROADCAST",
	1: "DISCOVER_INET_CONN_ESTABLISHED",
}
var DiscoveryEventKind_value = map[string]int32{
	"DISCOVER_OBSERVED_BROADCAST":    0,
	"DISCOVER_INET_CONN_ESTABLISHED": 1,
}

func (x DiscoveryEventKind) String() string {
	return proto.EnumName(DiscoveryEventKind_name, int32(x))
}
func (DiscoveryEventKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// DiscoveryEvent represents an observation of a peer over a network.
type DiscoveryEvent struct {
	// PeerId is the PublicKeyHash array.
	PeerId []byte `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Timestamp is when the event was observed.
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// Kind is the kind of discovery event.
	Kind DiscoveryEventKind `protobuf:"varint,3,opt,name=kind,enum=discovery.DiscoveryEventKind" json:"kind,omitempty"`
	// Inter is the observed interface.
	Inter uint32 `protobuf:"varint,4,opt,name=inter" json:"inter,omitempty"`
	// Extra info contains per-event-kind info.
	ExtraInfo []byte `protobuf:"bytes,5,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
}

func (m *DiscoveryEvent) Reset()                    { *m = DiscoveryEvent{} }
func (m *DiscoveryEvent) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryEvent) ProtoMessage()               {}
func (*DiscoveryEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DiscoveryEvent) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *DiscoveryEvent) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DiscoveryEvent) GetKind() DiscoveryEventKind {
	if m != nil {
		return m.Kind
	}
	return DiscoveryEventKind_DISCOVER_OBSERVED_BROADCAST
}

func (m *DiscoveryEvent) GetInter() uint32 {
	if m != nil {
		return m.Inter
	}
	return 0
}

func (m *DiscoveryEvent) GetExtraInfo() []byte {
	if m != nil {
		return m.ExtraInfo
	}
	return nil
}

// DiscoveryUDPPacket is a UDP discovery packet.
type DiscoveryUDPPacket struct {
}

func (m *DiscoveryUDPPacket) Reset()                    { *m = DiscoveryUDPPacket{} }
func (m *DiscoveryUDPPacket) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryUDPPacket) ProtoMessage()               {}
func (*DiscoveryUDPPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*DiscoveryEvent)(nil), "discovery.DiscoveryEvent")
	proto.RegisterType((*DiscoveryUDPPacket)(nil), "discovery.DiscoveryUDPPacket")
	proto.RegisterEnum("discovery.DiscoveryEventKind", DiscoveryEventKind_name, DiscoveryEventKind_value)
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/discovery/discovery.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x18, 0x85, 0x8d, 0x6e, 0x93, 0x05, 0x1d, 0x23, 0x0c, 0x2c, 0xe8, 0xb4, 0xec, 0xaa, 0x08, 0x6e,
	0xa8, 0xf7, 0xc2, 0xb6, 0x04, 0x2c, 0xca, 0x3a, 0xd2, 0x39, 0xf0, 0x2a, 0xb4, 0x69, 0xea, 0xc2,
	0x6c, 0x52, 0xd3, 0x74, 0xe8, 0x53, 0xf9, 0x8a, 0x62, 0xc5, 0x56, 0xef, 0xf2, 0x7d, 0x1c, 0xce,
	0x09, 0x3f, 0xbc, 0x7b, 0x91, 0x76, 0x53, 0xc6, 0x63, 0xae, 0xb3, 0x49, 0x5a, 0x16, 0xc2, 0xe8,
	0x58, 0x5b, 0xc9, 0x8b, 0xc9, 0x5b, 0x29, 0xf9, 0x15, 0xdf, 0x44, 0x4a, 0x89, 0xd7, 0x49, 0x22,
	0x0b, 0xae, 0x77, 0xc2, 0x7c, 0x34, 0xaf, 0x71, 0x6e, 0xb4, 0xd5, 0xa8, 0x5b, 0x8b, 0xd1, 0x27,
	0x80, 0x3d, 0xfc, 0x4b, 0x64, 0x27, 0x94, 0x45, 0x27, 0xf0, 0x30, 0x17, 0xc2, 0x30, 0x99, 0x38,
	0xc0, 0x05, 0xde, 0x11, 0xed, 0x7c, 0xa3, 0x9f, 0xa0, 0x33, 0xd8, 0xb5, 0x32, 0x13, 0x85, 0x8d,
	0xb2, 0xdc, 0xd9, 0x77, 0x81, 0xd7, 0xa2, 0x8d, 0x40, 0xd7, 0xb0, 0xb5, 0x95, 0x2a, 0x71, 0x0e,
	0x5c, 0xe0, 0xf5, 0x6e, 0x86, 0xe3, 0x66, 0xf4, 0x7f, 0xff, 0x83, 0x54, 0x09, 0xad, 0xa2, 0x68,
	0x00, 0xdb, 0x52, 0x59, 0x61, 0x9c, 0x96, 0x0b, 0xbc, 0x63, 0xfa, 0x03, 0x68, 0x08, 0xa1, 0x78,
	0xb7, 0x26, 0x62, 0x52, 0xa5, 0xda, 0x69, 0x57, 0x5f, 0xe8, 0x56, 0xc6, 0x57, 0xa9, 0x1e, 0x0d,
	0x20, 0xaa, 0x0b, 0x9f, 0xf0, 0x72, 0x19, 0xf1, 0xad, 0xb0, 0x97, 0xcf, 0x7f, 0x6c, 0x3d, 0x83,
	0x2e, 0xe0, 0x29, 0xf6, 0xc3, 0x79, 0xb0, 0x26, 0x94, 0x05, 0xb3, 0x90, 0xd0, 0x35, 0xc1, 0x6c,
	0x46, 0x83, 0x29, 0x9e, 0x4f, 0xc3, 0x55, 0x7f, 0x0f, 0x8d, 0xe0, 0x79, 0x1d, 0xf0, 0x17, 0x64,
	0xc5, 0xe6, 0xc1, 0x62, 0xc1, 0x48, 0xb8, 0x9a, 0xce, 0x1e, 0xfd, 0xf0, 0x9e, 0xe0, 0x3e, 0x88,
	0x3b, 0xd5, 0xd1, 0x6e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x95, 0x17, 0x62, 0x76, 0x01,
	0x00, 0x00,
}
