// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/route/route.proto
// DO NOT EDIT!

/*
Package route is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/quic-channel/route/route.proto

It has these top-level messages:
	Route
*/
package route

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import identity "github.com/fuserobotics/quic-channel/identity"
import signature "github.com/fuserobotics/quic-channel/signature"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Route is a circuit probe route.
type Route struct {
	// Hops are the hop steps in the route.
	Hop []*signature.SignedMessage `protobuf:"bytes,1,rep,name=hop" json:"hop,omitempty"`
	// Destination is the destination of the route.
	// Source can be inferred from the first hop.
	Destination *Route_Destination `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Route) GetHop() []*signature.SignedMessage {
	if m != nil {
		return m.Hop
	}
	return nil
}

func (m *Route) GetDestination() *Route_Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

// Hop is a hop in the probe route.
type Route_Hop struct {
	// Identity contains the identity of the peer.
	Identity *identity.Identity `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	// BackwardInterface is the interface in the direction of the originator, used for session routing.
	BackwardInterface uint32 `protobuf:"varint,2,opt,name=backward_interface,json=backwardInterface" json:"backward_interface,omitempty"`
	// ForwardInterface is the interface in the direction of the destination, used for verification.
	ForwardInterface uint32 `protobuf:"varint,3,opt,name=forward_interface,json=forwardInterface" json:"forward_interface,omitempty"`
	// Timestamp is the time the route probe was processed.
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Route_Hop) Reset()                    { *m = Route_Hop{} }
func (m *Route_Hop) String() string            { return proto.CompactTextString(m) }
func (*Route_Hop) ProtoMessage()               {}
func (*Route_Hop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Route_Hop) GetIdentity() *identity.Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Route_Hop) GetBackwardInterface() uint32 {
	if m != nil {
		return m.BackwardInterface
	}
	return 0
}

func (m *Route_Hop) GetForwardInterface() uint32 {
	if m != nil {
		return m.ForwardInterface
	}
	return 0
}

func (m *Route_Hop) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Destination is the destination of the route.
type Route_Destination struct {
	// Match by public key hash. Partials are accepted, with a minimum length.
	MatchPublicKey []byte `protobuf:"bytes,1,opt,name=match_public_key,json=matchPublicKey,proto3" json:"match_public_key,omitempty"`
}

func (m *Route_Destination) Reset()                    { *m = Route_Destination{} }
func (m *Route_Destination) String() string            { return proto.CompactTextString(m) }
func (*Route_Destination) ProtoMessage()               {}
func (*Route_Destination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Route_Destination) GetMatchPublicKey() []byte {
	if m != nil {
		return m.MatchPublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "route.Route")
	proto.RegisterType((*Route_Hop)(nil), "route.Route.Hop")
	proto.RegisterType((*Route_Destination)(nil), "route.Route.Destination")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/route/route.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x49, 0xd3, 0xfe, 0xfc, 0x4e, 0x55, 0xda, 0x59, 0x85, 0xe0, 0xa2, 0xb8, 0x2a, 0x4a,
	0x53, 0x50, 0x50, 0x10, 0x71, 0xe5, 0xc2, 0x22, 0x82, 0x8c, 0x0f, 0x50, 0x26, 0x93, 0xdb, 0xe4,
	0xd2, 0x66, 0x26, 0xce, 0xdc, 0x20, 0x7d, 0x2a, 0xdf, 0xc7, 0xa7, 0x91, 0x4e, 0xda, 0xa6, 0xb8,
	0xea, 0x26, 0xdc, 0xdc, 0xf3, 0x9d, 0x33, 0x73, 0x86, 0xdd, 0xe5, 0x48, 0x45, 0x9d, 0x26, 0xca,
	0x94, 0xd3, 0x45, 0xed, 0xc0, 0x9a, 0xd4, 0x10, 0x2a, 0x37, 0xfd, 0xac, 0x51, 0x4d, 0x54, 0x21,
	0xb5, 0x86, 0xd5, 0xd4, 0x9a, 0x9a, 0xa0, 0xf9, 0x26, 0x95, 0x35, 0x64, 0x78, 0xcf, 0xff, 0xc4,
	0x8f, 0x47, 0xd9, 0x31, 0x03, 0x4d, 0x48, 0xeb, 0xfd, 0xd0, 0x84, 0xc4, 0x4f, 0x47, 0xb9, 0x1d,
	0xe6, 0x5a, 0x52, 0x6d, 0xa1, 0x9d, 0x1a, 0xff, 0xe5, 0x4f, 0x87, 0xf5, 0xc4, 0xe6, 0x1e, 0xfc,
	0x8a, 0x85, 0x85, 0xa9, 0xa2, 0x60, 0x14, 0x8e, 0xfb, 0x37, 0x51, 0xd2, 0x82, 0x1f, 0x98, 0x6b,
	0xc8, 0xde, 0xc0, 0x39, 0x99, 0x83, 0xd8, 0x40, 0xfc, 0x81, 0xf5, 0x33, 0x70, 0x84, 0x5a, 0x12,
	0x1a, 0x1d, 0x75, 0x46, 0x81, 0xf7, 0x34, 0xed, 0x7c, 0x5c, 0xf2, 0xdc, 0xea, 0xe2, 0x10, 0x8e,
	0xbf, 0x03, 0x16, 0xbe, 0x98, 0x8a, 0x27, 0xec, 0xff, 0xae, 0x4b, 0x14, 0xf8, 0x00, 0x9e, 0xec,
	0xcb, 0xcd, 0xb6, 0x83, 0xd8, 0x33, 0x7c, 0xc2, 0x78, 0x2a, 0xd5, 0xf2, 0x4b, 0xda, 0x6c, 0x8e,
	0x9a, 0xc0, 0x2e, 0xa4, 0x02, 0x7f, 0xf4, 0x99, 0x18, 0xee, 0x94, 0xd9, 0x4e, 0xe0, 0xd7, 0x6c,
	0xb8, 0x30, 0xf6, 0x0f, 0x1d, 0x7a, 0x7a, 0xb0, 0x15, 0x5a, 0xf8, 0x82, 0x9d, 0x10, 0x96, 0xe0,
	0x48, 0x96, 0x55, 0xd4, 0x1d, 0x05, 0xe3, 0xae, 0x68, 0x17, 0xf1, 0x3d, 0xeb, 0x1f, 0xb4, 0xe1,
	0x63, 0x36, 0x28, 0x25, 0xa9, 0x62, 0x5e, 0xd5, 0xe9, 0x0a, 0xd5, 0x7c, 0x09, 0x4d, 0x81, 0x53,
	0x71, 0xee, 0xf7, 0xef, 0x7e, 0xfd, 0x0a, 0xeb, 0xf4, 0x9f, 0x7f, 0xe3, 0xdb, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x99, 0xa3, 0xd4, 0xed, 0x22, 0x02, 0x00, 0x00,
}
