// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/quic-channel/identity/identity.proto
// DO NOT EDIT!

/*
Package identity is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/quic-channel/identity/identity.proto

It has these top-level messages:
	Identity
*/
package identity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Identity contains just enough information to identify a peer.
type Identity struct {
	// CertPem contains each certificate in the chain, with the first certificate as the leaf.
	CertPem [][]byte `protobuf:"bytes,1,rep,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
}

func (m *Identity) Reset()                    { *m = Identity{} }
func (m *Identity) String() string            { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()               {}
func (*Identity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Identity) GetCertPem() [][]byte {
	if m != nil {
		return m.CertPem
	}
	return nil
}

func init() {
	proto.RegisterType((*Identity)(nil), "identity.Identity")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/identity/identity.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2b, 0x2d, 0x4e, 0x2d, 0xca, 0x4f, 0xca, 0x2f,
	0xc9, 0x4c, 0x2e, 0xd6, 0x2f, 0x2c, 0xcd, 0x4c, 0xd6, 0x4d, 0xce, 0x48, 0xcc, 0xcb, 0x4b, 0xcd,
	0xd1, 0xcf, 0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x84, 0x33, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x38, 0x60, 0x7c, 0x25, 0x55, 0x2e, 0x0e, 0x4f, 0x28, 0x5b, 0x48, 0x92, 0x8b, 0x23,
	0x39, 0xb5, 0xa8, 0x24, 0xbe, 0x20, 0x35, 0x57, 0x82, 0x51, 0x81, 0x59, 0x83, 0x27, 0x88, 0x1d,
	0xc4, 0x0f, 0x48, 0xcd, 0x4d, 0x62, 0x03, 0xeb, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x75,
	0xa8, 0x81, 0x51, 0x77, 0x00, 0x00, 0x00,
}
