// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/fuserobotics/quic-channel/signature/signature.proto

/*
Package signature is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/quic-channel/signature/signature.proto

It has these top-level messages:
	EncryptedMessage
	SignedMessage
	DataHash
*/
package signature

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ESignedMessageHash int32

const (
	ESignedMessageHash_HASH_SHA256 ESignedMessageHash = 0
)

var ESignedMessageHash_name = map[int32]string{
	0: "HASH_SHA256",
}
var ESignedMessageHash_value = map[string]int32{
	"HASH_SHA256": 0,
}

func (x ESignedMessageHash) String() string {
	return proto.EnumName(ESignedMessageHash_name, int32(x))
}
func (ESignedMessageHash) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// EncryptedMessage is an RSA PKI encrypted message.
type EncryptedMessage struct {
	HashType   ESignedMessageHash `protobuf:"varint,1,opt,name=hash_type,json=hashType,enum=signature.ESignedMessageHash" json:"hash_type,omitempty"`
	CipherText []byte             `protobuf:"bytes,2,opt,name=cipher_text,json=cipherText,proto3" json:"cipher_text,omitempty"`
}

func (m *EncryptedMessage) Reset()                    { *m = EncryptedMessage{} }
func (m *EncryptedMessage) String() string            { return proto.CompactTextString(m) }
func (*EncryptedMessage) ProtoMessage()               {}
func (*EncryptedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EncryptedMessage) GetHashType() ESignedMessageHash {
	if m != nil {
		return m.HashType
	}
	return ESignedMessageHash_HASH_SHA256
}

func (m *EncryptedMessage) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

// SignedMessage is a signed protobuf message.
type SignedMessage struct {
	Message       []byte             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SignatureSalt []byte             `protobuf:"bytes,2,opt,name=signature_salt,json=signatureSalt,proto3" json:"signature_salt,omitempty"`
	Signature     []byte             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	HashType      ESignedMessageHash `protobuf:"varint,4,opt,name=hash_type,json=hashType,enum=signature.ESignedMessageHash" json:"hash_type,omitempty"`
}

func (m *SignedMessage) Reset()                    { *m = SignedMessage{} }
func (m *SignedMessage) String() string            { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()               {}
func (*SignedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignatureSalt() []byte {
	if m != nil {
		return m.SignatureSalt
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetHashType() ESignedMessageHash {
	if m != nil {
		return m.HashType
	}
	return ESignedMessageHash_HASH_SHA256
}

// DataHash is the hash of some data.
type DataHash struct {
	Hash     []byte             `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	HashType ESignedMessageHash `protobuf:"varint,2,opt,name=hash_type,json=hashType,enum=signature.ESignedMessageHash" json:"hash_type,omitempty"`
}

func (m *DataHash) Reset()                    { *m = DataHash{} }
func (m *DataHash) String() string            { return proto.CompactTextString(m) }
func (*DataHash) ProtoMessage()               {}
func (*DataHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DataHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DataHash) GetHashType() ESignedMessageHash {
	if m != nil {
		return m.HashType
	}
	return ESignedMessageHash_HASH_SHA256
}

func init() {
	proto.RegisterType((*EncryptedMessage)(nil), "signature.EncryptedMessage")
	proto.RegisterType((*SignedMessage)(nil), "signature.SignedMessage")
	proto.RegisterType((*DataHash)(nil), "signature.DataHash")
	proto.RegisterEnum("signature.ESignedMessageHash", ESignedMessageHash_name, ESignedMessageHash_value)
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/quic-channel/signature/signature.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xf4, 0x2d, 0xda, 0x4e, 0xff, 0x58, 0xf6, 0x94, 0x83, 0x62, 0x29, 0x14, 0x8a,
	0x60, 0x02, 0x15, 0x3d, 0x78, 0x10, 0x0a, 0x16, 0x72, 0xf1, 0x92, 0xf4, 0xe4, 0x25, 0x6c, 0xd6,
	0x31, 0xbb, 0x90, 0x66, 0x63, 0x76, 0x02, 0xcd, 0x57, 0xf2, 0x53, 0x4a, 0x52, 0x9b, 0x10, 0x3c,
	0xf5, 0x36, 0xfb, 0xdb, 0x87, 0xdf, 0xec, 0xc3, 0xc2, 0x4b, 0xac, 0x48, 0x16, 0x91, 0x23, 0xf4,
	0xde, 0xfd, 0x2c, 0x0c, 0xe6, 0x3a, 0xd2, 0xa4, 0x84, 0x71, 0xbf, 0x0a, 0x25, 0xee, 0x85, 0xe4,
	0x69, 0x8a, 0x89, 0x6b, 0x54, 0x9c, 0x72, 0x2a, 0x72, 0x6c, 0x27, 0x27, 0xcb, 0x35, 0x69, 0x36,
	0x6c, 0xc0, 0x42, 0xc3, 0x6c, 0x9b, 0x8a, 0xbc, 0xcc, 0x08, 0x3f, 0xde, 0xd0, 0x18, 0x1e, 0x23,
	0x7b, 0x86, 0xa1, 0xe4, 0x46, 0x86, 0x54, 0x66, 0x68, 0x5b, 0x73, 0x6b, 0x35, 0x5d, 0xdf, 0x38,
	0xad, 0x63, 0x1b, 0xa8, 0x38, 0x6d, 0xd2, 0x1e, 0x37, 0xd2, 0x1f, 0x54, 0xf9, 0x5d, 0x99, 0x21,
	0xbb, 0x85, 0x91, 0x50, 0x99, 0xc4, 0x3c, 0x24, 0x3c, 0x90, 0xdd, 0x9b, 0x5b, 0xab, 0xb1, 0x0f,
	0x47, 0xb4, 0xc3, 0x03, 0x2d, 0xbe, 0x2d, 0x98, 0x74, 0x04, 0xcc, 0x86, 0xcb, 0xfd, 0x71, 0xac,
	0x97, 0x8d, 0xfd, 0xd3, 0x91, 0x2d, 0x61, 0xda, 0xac, 0x0d, 0x0d, 0x4f, 0x4e, 0xbe, 0x49, 0x43,
	0x03, 0x9e, 0x10, 0xbb, 0x86, 0xb6, 0x90, 0xfd, 0xbf, 0x4e, 0xb4, 0xa0, 0xdb, 0xa6, 0x7f, 0x56,
	0x9b, 0xc5, 0x3b, 0x0c, 0x5e, 0x39, 0xf1, 0x8a, 0x32, 0x06, 0xfd, 0x8a, 0xff, 0xbe, 0xb1, 0x9e,
	0xbb, 0xee, 0xde, 0x59, 0xee, 0xbb, 0x25, 0xb0, 0xbf, 0xf7, 0xec, 0x0a, 0x46, 0xde, 0x26, 0xf0,
	0xc2, 0xc0, 0xdb, 0xac, 0x1f, 0x9f, 0x66, 0xff, 0xa2, 0x8b, 0xfa, 0xcb, 0x1e, 0x7e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xde, 0x0f, 0x76, 0x97, 0xf4, 0x01, 0x00, 0x00,
}
